import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import QueryProvider from "@/lib/providers/QueryProvider";
import ReduxProvider from "@/lib/providers/ReduxProvider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <QueryProvider>
          <ReduxProvider>
            <Header />
            <div className="m-auto md:max-w-container-md lg:max-w-container-lg 2xl:max-w-container-2xl">
              {children}
            </div>
          </ReduxProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
